### ISSUE TITLE
Minor corrections on Exercise 6.8.13

### ISSUE THREAD

**Issue by vashcast** [telmo-correa/all-of-statistics#21]
In the current status of the solution it is used that $\mathbb{P}(Z_i>x/n)=\int_0^{x/n} f(u) \rm{d}u$, $F(0)=1$, and $F'(0)= -\lambda$. None of these statements are correct.

The correct statements are:
- $\mathbb{P}(Z_i>x/n)=\int_0^{\infty} f(u) \rm{d}u - \int_0^{x/n} f(u) \rm{d}u= 1 - \int_0^{x/n} f(u) \rm{d}u$ = 1 - F(x/n). 

- $F(0) = \int_0^0 f(u) \rm{d}u = 0$.

- $F'(0) = \lim_{x \to 0} f(x) = \lambda$.

All these changes lead us to the same expected result.

**Comment by telmo-correa** [comment]
fixed, thank you
