### ISSUE TITLE
Exercise 8.5.8 Standard Error mistake

### ISSUE THREAD

**Issue by redfungus** [telmo-correa/all-of-statistics#4]
Hi! 

First of all thanks for this repo! It's been a big help for self-studying the book.
In question 8.5.8 I think  `se = r.std()` should be replaced by `se = r.sem()` or `math.sqrt(r.var() / len(r))`. The std calculates the standard deviation of the values themselves where as we want the standard error of the mean estimate which is calculated using: 
![image](https://user-images.githubusercontent.com/13507904/120118611-bd95da80-c193-11eb-90b7-63af6d0072da.png)

**Comment by telmo-correa** [comment]
You are correct; thank you for catching this.  I just pushed a fix to exercise 8.5.8 fixing this issue.
