### ISSUE TITLE
Exercise 3.14.14 contains an error.

### ISSUE THREAD

**Issue by ksmirn0v** [telmo-correa/all-of-statistics#7]
Hello,

The right answer for f(r) should be 2*r instead of 2*pi*r. Otherwise, you can't normalize f(r) to 1.

Best wishes,
Kirill

**Comment by telmo-correa** [comment]
Updated, thank you.

**Comment by ksmirn0v** [comment]
@telmo-correa 

I think, the solution still contains an error.
F(r) has to be r^2.

It is because f(x,y) = 1/pi for x^2 + y^2 <= 1.

Best,
Kirill

**Comment by telmo-correa** [comment]
Updated.

If there are further changes required, please make a PR.
